bot:
  token: 377464414:AAEq-w7-D89rKdXjFjildYgBn2KwvuCGVrc
  username: pacchio97_bot

logging:
  level:
    org.springframework.web: ERROR
    com.mytelegrambot: DEBUG
#  file: C:\Development\workspace\java-project\my-telegram-bot\bot-resources\application.log
  file: /home/pi/bot-resources/application.log